### ISSUE TITLE
Strong-naming assembly

### ISSUE THREAD

**Issue by hrafnkellpalsson** [DataDog/dogstatsd-csharp-client#11]
Have you considered strong-naming the StatsdClient.dll assembly? I'm trying to use your NuGet package with my own strongly-named assembly, which doesn't work.

(When compiling my project I get an error:
"Assembly generation failed -- Referenced assembly 'StatsdClient' does not have a strong name")

**Comment by LeoCavaille** [comment]
Hey @hrafnkellpalsson thanks for reporting this. We'll have a look at what's involved.

**Comment by yannmh** [comment]
Thanks for your suggestion @hrafnkellpalsson.
dogstatsd-csharp-client v2.0.2 now uses strong named assemblies. Feel free to re-open this ticket if you're still experiencing issues.
