### ISSUE TITLE
100% CPU load with version 5.0.0

### ISSUE THREAD

**Issue by PSanetra** [DataDog/dogstatsd-csharp-client#119]
Using version 5.0.0 of this library causes 1 CPU to run at 100% load.

This is not happening with version 4.0.1.
![cpu_load](https://user-images.githubusercontent.com/7327745/82201284-6adadf00-9900-11ea-8f26-df0931edb22c.png)

**Comment by ogaca-dd** [comment]
@PSanetra ,

Thank you for reporting this issue.
https://github.com/DataDog/dogstatsd-csharp-client/pull/121 should fix it.

**Comment by ogaca-dd** [comment]
@PSanetra ,

It should be fixed by [DogStatsD-CSharp-Client 5.0.1](https://www.nuget.org/packages/DogStatsD-CSharp-Client).
Let us know if you still have the issue.

**Comment by PSanetra** [comment]
Looks good with 5.0.1 :thumbsup:
