### ISSUE TITLE
Cannot Flush without Disposing

### ISSUE THREAD

**Issue by danny-zegel-zocdoc** [DataDog/dogstatsd-csharp-client#141]
I need to be able to flush my metrics without disposing.

I am using [Dogstatsd](https://github.com/DataDog/dogstatsd-csharp-client/blob/master/src/StatsdClient/Dogstatsd.cs) by calling `Dogstatsd.Configure()` at app startup and then calling the various metric functions during execution.

My particular use-case is such that I need to flush periodically because the app may or may not terminate at certain points and I will loose metrics that were not flushed. Currently the only way I see to flush metrics is by calling `Dogstatsd.Dispose()` but if I dispose, I obviously can't continue using `Dogstatsd` and I am unable to add a hook to Dispose when it actually terminates.

Is there a way to flush without disposing that I am not seeing?

**Comment by ogaca-dd** [comment]
@danny-zegel-zocdoc ,

In https://github.com/DataDog/dogstatsd-csharp-client/pull/144, I have introduced a `Flush` method.

**Comment by danny-zegel-zocdoc** [comment]
> #144

@ogaca-dd 
This is greatly appreciated!
Do you have an idea when this will be released?

**Comment by ogaca-dd** [comment]
@danny-zegel-zocdoc 
It will be released soon, 1 or 2 days after https://github.com/DataDog/dogstatsd-csharp-client/pull/144 will be internally reviewed.
