### ISSUE TITLE
DogStatsdService Best Practices for Optimization

### ISSUE THREAD

**Issue by veely** [DataDog/dogstatsd-csharp-client#152]
Hello,

I would like to know if there are any problems with creating a new instance of DogStatsdService and dispose it for every metric update. For example I have a method like this:

```
        public static void IncrementSuccessCounter()
        {
            using (var dogStatsdService = new DogStatsdService())
            {
                dogStatsdService.Configure(dogstatsdConfig);
                dogStatsdService.Increment(DatadogStatsdCounters.SUCCESS, tags: new[] { "service: " + Utilities.GetAppSetting("DD_SERVICE_NAME") });
            }
        }
```

Is there a better way of doing this?

**Comment by veely** [comment]
bump

**Comment by ogaca-dd** [comment]
Hi @veely ,

Sorry for my late answer.

`DogStatsdService` is thread safe and designed to be instantiated once by application. Creating a new instance of `DogStatsdService` for each metric is very inefficient.

**Comment by ogaca-dd** [comment]
Closed as the question is answered.
