### ISSUE TITLE
Need for try/catch?

### ISSUE THREAD

**Issue by brendonparker** [DataDog/dogstatsd-csharp-client#157]
This isn't so much an issue, as a question. Although the answer isn't super clear, so maybe _that's_ the issue :)

*Is there a need to wrap usage of DogStatsd in try/catch?*

To borrow from sample in readme:
```csharp
// The code is located under the StatsdClient namespace
using StatsdClient;

// ...

var dogstatsdConfig = new StatsdConfig
{
    StatsdServerName = "127.0.0.1",
    StatsdPort = 8125,
};

DogStatsd.Configure(dogstatsdConfig);
// Like this?
try
{
    DogStatsd.Increment("example_metric.increment", tags: new[] { "environment:dev" });
}
catch (Exception ex)
{
}
// ...
```

This came up when adding this in to our application during code review. I hate adding this kind of try/catch, but the idea is this should be like logging; any failures should do so silently.

**Comment by ogaca-dd** [comment]
@brendonparker ,

> This isn't so much an issue, as a question. Although the answer isn't super clear, so maybe that's the issue :)

Indeed, the XML comments should be explicit about whether a method is expected to throw an exception or not.

You do not need to add `try` / `catch` around most methods of `DogStatsd` or `DogStatsdService`.  For example, `DogStatsd.Increment` creates an internal metric and push it in to a `ConcurrentQueue`. Another thread performs some operations on this metric and send it over the network. The exceptions thrown in this thread are caught at https://github.com/DataDog/dogstatsd-csharp-client/blob/master/src/StatsdClient/Worker/AsynchronousWorker.cs#L145-L148. `DogStatsd.Increment` is not expected to throw an exception.

Note : 
- `DogStatsd.Configure` and `DogStatsdService.Configure` can throw an exception.
- Methods taking `Action` or `Func<T>` like `DogStatsd.Time` throw an exception if the callback throws an exception.

**Comment by brendonparker** [comment]
Thank you for the clarification. This was the conclusion I came to as well.
