### ISSUE TITLE
DogStatsD starts increasing metrics indefinitely if it fails to flush metrics

### ISSUE THREAD

**Issue by halkar** [DataDog/dogstatsd-csharp-client#176]
Recently we faced a problem with our DataDog metrics. We have several metrics we are sending from our ASP.Net Core app, and most of them are simple counter metrics. We call the `IDogStatsd.Increment` method. 99.999% of all metrics are OK and sent to DataDog without issues. But sometimes we generate a metric that doesn't fit the buffer, and then we get an `InvalidOperationException`.
See code here https://github.com/DataDog/dogstatsd-csharp-client/blob/02d6a27cb6458f44600564114b85a3edb5678aed/src/StatsdClient/Bufferize/BufferBuilder.cs#L62
It's not a problem by itself, and we've already fixed the issue on our side. But other counters using `IDogStatsd.Increment` go nuts when it happens (all counter metrics are constantly increasing).
<img width="914" alt="Screen Shot 2022-06-20 at 12 47 15 pm" src="https://user-images.githubusercontent.com/1992396/174516374-1c7decc2-7a1d-4a6c-91c1-a6f73fd53a3f.png">
Looks like DogStatsD keeps trying to flush the metrics but keeps crashing on the broken one. The only way to solve this problem is to kill the service. I guess the broken metric should be excluded rather than retried every time. Looks like the problem started in version 7.0.0. Also, as the flush process runs asynchronously, we cannot handle this exception, making it hard to investigate the issue. DogStatsD doesn't return or write the exception to logs.

**Comment by ogaca-dd** [comment]
@halkar,
Thank you for reporting this issue. I will try to reproduce the issue and create a new release that fix the problem.

**Comment by ogaca-dd** [comment]
[#178 ](https://github.com/DataDog/dogstatsd-csharp-client/pull/178)should fix this issue. I am going to create a new release at the beginning of next week.

**Comment by halkar** [comment]
Awesome! Thanks @ogaca-dd

**Comment by halkar** [comment]
Thanks a lot @ogaca-dd
