### ISSUE TITLE
Does this support the REST API?

### ISSUE THREAD

**Issue by red8888** [DataDog/dogstatsd-csharp-client#180]
I use GCP cloud run so we can't run a local agent.

We could write metrics directly to datadog with the REST API, but we'd prefer to use the statsd protocol. 

Does this library support writing statsd metrics to datadog with the REST API instead of the agent?

**Comment by ogaca-dd** [comment]
Hello @red8888,

This library is only designed to send metrics to the Agent.

**Comment by ogaca-dd** [comment]
Close this issue. Feel free to reopen it if you have more question on this topic.
