### ISSUE TITLE
Service checks?

### ISSUE THREAD

**Issue by mausch** [DataDog/dogstatsd-csharp-client#23]
Is is possible to send [service checks](http://docs.datadoghq.com/guides/dogstatsd/#service-checks) using `DogStatsd`? It doesn't seem to be available in https://github.com/DataDog/dogstatsd-csharp-client/blob/master/src/StatsdClient/Statsd.cs , is there any particular reason for this?

Should I use `StatsdUDP` instead? Is it worth adding a new `ICommandType` for this?

**Comment by yannmh** [comment]
Apologies for the late answer @mausch.

As you pinpointed, it is indeed possible to send service checks using `Dogstatsd`, the packet format being the one described in your [link](http://docs.datadoghq.com/guides/dogstatsd/#service-checks).  
A couple of Dogstatsd libraries already support it: [datadogpy](https://github.com/DataDog/datadogpy), [java-dogstatsd-client](https://github.com/DataDog/java-dogstatsd-client) for instance.

We can work on extending the support to `Dogstatsd` too. @mausch would this feature help you and your team ?

Yann

**Comment by mausch** [comment]
Yes, I'm already working around this by sending a datagram with that format. 
However I think this falls under the scope of this library, i.e. the library should provide a strongly typed interface, escape or validate arguments as needed, etc.

**Comment by nathanrobb** [comment]
Is this now closed in #29 ?

**Comment by yannmh** [comment]
Yes 🎉 . Thanks!
