### ISSUE TITLE
Events through API endpoint

### ISSUE THREAD

**Issue by mausch** [DataDog/dogstatsd-csharp-client#25]
When sending events, I get many errors like this in the Dogstatsd log in the Datadog agent:

```
2015-12-07 10:57:09 Coordinated Universal Time | ERROR | dogstatsd(dogstatsd.pyc:311) | Error receiving datagram
Traceback (most recent call last):
  File "dogstatsd.pyc", line 298, in start
error: [Errno 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
```

I've been talking about this with Datadog support and they recommend using the Event HTTP endpoint instead:  http://docs.datadoghq.com/api/#events . Can we get that implemented in this library?

Thanks

**Comment by yannmh** [comment]
Thanks for reporting @mausch.

It looks like we are hitting some kind of limit here. Let's keep `dogstatsd-csharp-client` a StatsD client only and makes it gracefully handle this scenario.

Can you tell me more about the events causing this issue ? Do they share any common pattern ? I am particularly curious to know how "big" they are.

Yann

**Comment by mausch** [comment]
You can find more information about these messages in https://github.com/serilog/serilog-sinks-datadog/issues/2 .

**Comment by yannmh** [comment]
@mausch I was able to reproduce the issue.

**DogStatsD C#**
When buffering commands (`Add()`) and flushing (`Send()`), DogStatsD C#  checks the payload size and attempts to properly split it when its size exceeds `StatsdUDP.maxUDPPacketSize`. If no split resolves the problem (i.e. chunks' sizes are still above the limit), it falls back and send the vanilla payload.

By default, `StatsdUDP.maxUDPPacketSize` is set to `dogstatsdConfig.DefaultStatsdMaxUDPPacketSize==512` bytes. However DogStatsD C# can potentially send payload size up to `8192` bytes (= DogStatsD server buffer size). 

This discrepancy should not be permitted as it leads to un-splittable payloads. I'll work on a fix for the `2.2.0` release.  

**Short-term fix**
In the meantime, a solution is to set the `StatsdUDP.maxUDPPacketSize` to match the maximum value for DogStatsD C# payload size (`8192`), i.e.
```c#
            StatsdUDP udp = new StatsdUDP(dogstatsdConfig.StatsdServerName, dogstatsdConfig.StatsdPort, 8192);
            using (udp)
            {
                Statsd s = new Statsd(udp);
                s.Add("title", text);
                [...]
            }
```

**Comment by DanielVukelich** [comment]
The problem is that UDP datagram sizes are dependent on the network medium through which they are being transported.  While this probably won't be an issue for users sending stats through localhost, network limited MTUs will start to apply if metrics are sent to another machine.  IPv4's minimum buffer reassembly size is 576B.  Including the space for headers, 512B  is about the largest size datagram that will always be supported.

If people need a larger limit, we should make this configurable.  Otherwise, we risk breaking functionality.

**Comment by yannmh** [comment]
So the max UDP datagram size is configurable via `StatsdConfig`:
```c#
var dogstatsdConfig = new StatsdConfig
{
    StatsdServerName = "127.0.0.1",
    StatsdPort = 8125, // Optional; default is 8125
    StatsdMaxUDPPacketSize = 512 // Optional; in bytes (default to 512)
};
```
It's set by default to 512 bytes.  

Any payload that is is bigger than that will be split (when possible), or sent as it is (up to 8KB). 

We are also adding a `StatsdTruncateIfTooLong`option to `StatsdConfig` to instrument the code to truncate any event and service when their size exceeds 8kB: https://github.com/DataDog/dogstatsd-csharp-client/pull/55.
This will be out with 3.1.

**Comment by yannmh** [comment]
I believe the issue is now mitigated with #55. Please feel free to re-open if needed.
