### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by jlandersen** [DataDog/dogstatsd-csharp-client#27]
Hi

Following the release of .NET Core, it would be great to extend support for this / netstandard.

**Comment by yannmh** [comment]
Thanks for the bringing suggestion to the table @jlandersen !

I am not familiar with .NET Core. Would you know, by any chance, what are the requirement to achieve this port and how much of a work it would be ? 

Yann

**Comment by jlandersen** [comment]
Hi Yann

I can't speak of how much work it will be for this library specifically, but here are some details on porting to .NET Core:
https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/
https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/

Also, I noticed that this library is a fork from https://github.com/Pereingo/statsd-csharp-client, they currently have an issue with a PR that enables .NET Core support, so you might be able to just incorporate most of the needed changes from there!

**Comment by wjdavis5** [comment]
+1

**Comment by wjdavis5** [comment]
I was wondering if there had been any further investigation into this. As a datadog customer we are prepping our first .NET Core Release to production in the coming weeks.

**Comment by rykelleydhi** [comment]
we are not a customer but would interested in switching if you there .net core support

**Comment by wjdavis5** [comment]
@rykelleydhi - I have an unofficial port that we have been using in production for some time now:
https://www.nuget.org/packages/DogStatsD-CSharp-Client-Core/

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/dogstatsd-csharp-client/pull/39. This is coming out with the `3.0.0` release.

**Comment by agrebenyuk** [comment]
DogStatsD-CSharp-Client-Core has a reference to non-Core (1.0.0) and non-Net standard NUnit Dll ???
