### ISSUE TITLE
Output on console

### ISSUE THREAD

**Issue by davidebettio** [DataDog/dogstatsd-csharp-client#33]
With versions 2.2.0 every time is there a call to:

`DogStatsd.Counter`

in console I see these strings:

```
Command length 25
MaxUDP size 512
```

**Comment by yannmh** [comment]
Thanks for reporting @davidebettio,

Could you confirm that this was not the case prior to the `2.2.0` version please?

**Comment by davidebettio** [comment]
Yes, prior to the version 2.2.0 all is ok.

**Comment by Friss** [comment]
I'm seeing the same thing in my console but with `Histogram` and `Gauge` Version `2.1.1` does not have the same effect

**Comment by albertofem** [comment]
I think I found the issue. The Release code is compiled using the "TRACE" define:

https://github.com/DataDog/dogstatsd-csharp-client/blob/master/src/StatsdClient/StatsdClient.csproj#L30

This is telling the low level socket library to output trace information, specifically in the method "SendTo" (https://github.com/DataDog/dogstatsd-csharp-client/blob/master/src/StatsdClient/StatsdUDP.cs#L86) as per the following documentation:

https://msdn.microsoft.com/en-us/library/eae4f5y0(v=vs.110).aspx

> This member outputs trace information when you enable network tracing in your application. For more information, see Network Tracing in the .NET Framework.

If you read the documentation, you can see how setting the TRACE constant will enable the tracing:

https://msdn.microsoft.com/en-us/library/64yxa344(v=vs.110).aspx

The solution is easy enough: remove the "TRACE" from Release builds. I made a PR: https://github.com/DataDog/dogstatsd-csharp-client/issues/33

I tried the solution by compiling without the trace and linking against my program and it works, no more trace info is being output.
