### ISSUE TITLE
GetIpv4Address() in StatsdUDP may resolve incorrectly

### ISSUE THREAD

**Issue by celenechang** [DataDog/dogstatsd-csharp-client#4]
in GetIpv4Address(),

`int positionForIpv4 = addressList.Length - 1`

is not always pulling the correct IP address.

Something like this may be better: 
http://stackoverflow.com/questions/6803073/get-local-ip-address-c-sharp/13533122#13533122

**Comment by remh** [comment]
Closing, we didn't encounter that issue. Didn't happen in a while.
