### ISSUE TITLE
IDogStatsd interface is not used

### ISSUE THREAD

**Issue by cjzness** [DataDog/dogstatsd-csharp-client#43]
It is not currently possible to mock the DogStatsd client as it does not implement the IDogStatsd interface.

**Comment by yannmh** [comment]
Thanks for reporting @cjzness,

You're right, that's an oversight on our part. We'll fix this with the next release.

**Comment by wholroyd** [comment]
Ran into this issue as well. Is there a timeframe for 3.1 being available?
