### ISSUE TITLE
Assembly is not Strong-Named

### ISSUE THREAD

**Issue by keslerm** [DataDog/dogstatsd-csharp-client#45]
It looks like the 3.0.0 is not Strong-Named which is causing problems with my own Strong Named assembly. 

Would it be possible to get these assemblies signed in future releases?

**Comment by yannmh** [comment]
@keslerm, thanks for letting us know. We'll work on bringing this back with the 3.1 milestone.

**Comment by SimonPStevens** [comment]
Looks like the 3.1 nuget package is not strong named. Any news on if this planned for a future release?

**Comment by ogaca-dd** [comment]
@keslerm @SimonPStevens : The latest version of the package uses a strong-named assembly.
https://github.com/DataDog/dogstatsd-csharp-client/blob/master/CHANGELOG.md#340--11-15-2019

Feel free to reopen this issue or create a new one if the issue is not fixed for you.
