### ISSUE TITLE
NuGet 2.2.0 package doesn't support ServiceCheck, even though it's in the release notes

### ISSUE THREAD

**Issue by christopherliu** [DataDog/dogstatsd-csharp-client#46]
Just saw the update for ServiceCheck here: https://github.com/DataDog/dogstatsd-csharp-client/pull/29

We were using 2.2.0 from NuGet and couldn't find ServiceCheck in DogStatsD (double-checked on ILSpy).

Not urgent since we can use other versions, but I'm curious why that's not in there when it's reported as part of the changes. Thanks!

**Comment by yannmh** [comment]
Sorry for the late answer @christopherliu ,

I confirm that ServiceCheck support is not included in the 2.2.0 Nuget package, besides being listed in the CHANGELOG. I am not sure how that happened, I suspect something went wrong in the building and/or the release process. I am sorry for the inconvenience.

I'll update the CHANGELOG and the release notes to reflect that. On a better note, this kind of issues are less likely to happen now as we use AppVeyor to automate the building process.
