### ISSUE TITLE
AppVeyor builds failing

### ISSUE THREAD

**Issue by DanielVukelich** [DataDog/dogstatsd-csharp-client#51]
It looks like your appveyor build environment is broken. 

Looking at the logs for #47  and #50, you can see that it's complaining about 
`C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props`
being missing.

**Comment by pdpurcell** [comment]
This pull request should fix it: #52

**Comment by yannmh** [comment]
This was fixed with #52. Thanks again @pdpurcell.
