### ISSUE TITLE
NuGet Package has NUnit dependency

### ISSUE THREAD

**Issue by AirbornePorcine** [DataDog/dogstatsd-csharp-client#8]
The 2.0.0 NuGet package has a dependency on NUnit although it's only necessary to run the tests.

It can be worked around for the moment by running:

    Install-Package Dogstatsd-CSharp-Client -IgnoreDependencies

**Comment by yannmh** [comment]
Thank you @AirbornePorcine for letting us know. I'll fix it and re-release the package.

**Comment by yannmh** [comment]
Fixed by 7b4577aa1e2ae29309af229a3a1882ea6301a482 and released in DogStatsD C# 2.0.1.
