### ISSUE TITLE
Missing UDS (Unix Domain Socket) support

### ISSUE THREAD

**Issue by danopia** [DataDog/dogstatsd-csharp-client#85]
Hey, I've been developing a C# application using .NET Core on MacOS, and am deploying to a Kubernetes cluster on EC2 Linux. I want to emit custom metrics to my cluster's Datadog agents. The Datadog documentation for containerized applications suggests that UDS is the simplest way to configure a Kubernetes application for custom metrics: https://docs.datadoghq.com/agent/kubernetes/dogstatsd/

Emitting over UDP is a more complex configuration in containerized environment, and also means the application needs to include origin tagging information in each packet. These docs talk more generally of the dogstatsd UDS feature and why it exists. https://docs.datadoghq.com/developers/dogstatsd/unix_socket/

I know that Unix Domain Sockets sound like a weird request of a C# project, but with the proliferation of dotnetcore there are more and more people running .NET applications in Linux ecosystems and containerized environments.

Here's an example of another DD library's changes for UDS: https://github.com/DataDog/dogstatsd-ruby/pull/61/files

**Comment by mohag** [comment]
Some new Windows versions [also support Unix sockets](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/). (No SOCK_DGRAM yet though...)

**Comment by ogaca-dd** [comment]
Hey,

[DogStatsD-CSharp-Client 4.0.0](https://github.com/DataDog/dogstatsd-csharp-client/releases/tag/4.0.0) adds UDS support. 
- Nuget Package: https://www.nuget.org/packages/DogStatsD-CSharp-Client/
- Documentation: [Unix domain socket support](https://github.com/DataDog/dogstatsd-csharp-client/tree/master#unix-domain-socket-support).

Let us know if you have any issues.

**Comment by danopia** [comment]
Hello, I upgraded to 4.0.0 and noticed that the UDS support fails when configured using the `DD_AGENT_HOST` environment variable. The UDS entrypoint was based off the UDP entrypoint, however the UDP implementation doesn't have this problem because it internally falls back to re-reading the `DD_AGENT_HOST` environment variable using its own `GetHostNameFromEnvVar`. The UDS implementation does not have that logic and instead throws `System.ArgumentException: unixSocket must start with unix://`.

This minimal diff should resolve the problem however I am not sure of a good way to test it and therefor I don't really want to PR it as-is:

```diff
diff --git a/src/StatsdClient/DogStatsdService.cs b/src/StatsdClient/DogStatsdService.cs
index aa32081..0e50109 100644
--- a/src/StatsdClient/DogStatsdService.cs
+++ b/src/StatsdClient/DogStatsdService.cs
@@ -31,7 +31,7 @@ namespace StatsdClient
 
                 if (statsdServerName.StartsWith(StatsdUnixDomainSocket.UnixDomainSocketPrefix))
                 {
-                    var statsdUds = new StatsdUnixDomainSocket(config.StatsdServerName, config.StatsdMaxUnixDomainSocketPacketSize);
+                    var statsdUds = new StatsdUnixDomainSocket(statsdServerName, config.StatsdMaxUnixDomainSocketPacketSize);
                     _disposable = statsdUds;
                     statsdSender = statsdUds;
                 }
```

**Comment by ogaca-dd** [comment]
@danopia : Thank you for reporting this issue. https://github.com/DataDog/dogstatsd-csharp-client/pull/106 should fix the issue.

**Comment by ogaca-dd** [comment]
@danopia : https://github.com/DataDog/dogstatsd-csharp-client/releases/tag/4.0.1
